### ISSUE TITLE
Bug: dropdown not visible in Manage access view, Firefox

### ISSUE THREAD

**Issue by davdavf** [whitespace-se/matomo-modern-theme#16]
On //MATOMO-URL/index.php?module=UsersManager, the last Role selector dropdown for websites is not shown correctly:
![image](https://user-images.githubusercontent.com/15054744/110461774-26f3d900-80d0-11eb-9b4f-746ae3cfd43a.png)

Using Matomo 4.2.1, Firefox 83.0. 
(Chrome 88 does not have this issue.)

**Comment by degeer** [comment]
Thanks @davdavf. We have released a new version - v1.0.6 - that should fix this issue.

**Comment by davdavf** [comment]
Works perfectly, thanks! :-)
