### ISSUE TITLE
Segment name cut off

### ISSUE THREAD

**Issue by webberian** [whitespace-se/matomo-modern-theme#18]
Segment names are cut off for certain characters:
![image](https://user-images.githubusercontent.com/15054744/114561267-b52e2280-9c6d-11eb-8e80-a8ac14aac5d5.png)

![image](https://user-images.githubusercontent.com/15054744/114561839-3c7b9600-9c6e-11eb-85a9-c9cf083fc93d.png)

In the above examples, the "q" and "g".

Matomo 4.2.1 tested with Firefox and Chrome.

**Comment by degeer** [comment]
Thanks! We have fixed this in the latest release - 1.0.7.
