### ISSUE TITLE
Icons font not loading, icon missing

### ISSUE THREAD

**Issue by nhoizey** [whitespace-se/matomo-modern-theme#19]
I have an issue with the icons font not loading, with a 403 error.

![image](https://user-images.githubusercontent.com/78213/137125263-c458ca0a-0621-4712-b82b-b97881136b88.png)

![image](https://user-images.githubusercontent.com/78213/137125280-4eee7329-39b9-4579-9198-b23db735e468.png)

I changed the paths in `plugins/Modern/stylesheets/base/icons.css`, from `url('plugins/Modern/fonts/matomo.woff2?70exlr')` to `url('../../fonts/matomo.woff2?70exlr')` for example, and the font is now loaded, but the icon is still missing.

**Comment by degeer** [comment]
Hello,
We are not able reproduce this bug. Could you give us some more information? e.g. version of Matomo, are you running Matomo as a standalone installation? 

The [modern](https://github.com/whitespace-se/matomo-modern-theme/blob/master/stylesheets/base/icons.css) theme has the same config the [Morpheus](https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/Morpheus/stylesheets/base/icons.css) theme.

**Comment by nhoizey** [comment]
I'm using Matomo 4.6.1 as a standalone installation.

Icons are now visible, so maybe a Matomo upgrade fixed the issue.
