### ISSUE TITLE
New dark mode cannot be switched off

### ISSUE THREAD

**Issue by LeoniePhiline** [whitespace-se/matomo-modern-theme#23]
No matter what I choose in plugin settings (auto, dark, light), Modern v1.1.1 stays dark (at least at night, while my auto-changing iPhone is also in dark mode).

**Comment by 54mu3l** [comment]
Same problem here. I cannot turn off the dark mode at all.

**Comment by degeer** [comment]
Thank you for your comments. We will try to come up with a solution for this problem. In the meantime - you can see that the changes have taken effect by doing a "hard refresh" in the browser.

**Comment by johanwestin** [comment]
A fix for this has been commited and will be released in the next version. 👍
