### ISSUE TITLE
Dark mode does not darken or brighten all elements

### ISSUE THREAD

**Issue by LeoniePhiline** [whitespace-se/matomo-modern-theme#24]
- User cards are bright despite dark mode
- User card activity label is dark and hardly visible on the dark background 
- Charts have light background 
- Spark lines are black and basically invisible 

Not sure if that’s a bug just on my system, or if maybe the dark theme is just not yet finished. 

Since the dark mode cannot be switched off right now (plugin settings do not affect coloring), I am either stuck or need to uninstall this otherwise very beautiful theme. 

![9C573279-EDB0-4A3D-A4A5-0B8A8CF1CEA3](https://user-images.githubusercontent.com/22329650/192069937-8f947397-7566-41ca-b14a-01af50e070ff.png)

**Comment by 54mu3l** [comment]
@LeoniePhiline You're not the only one. I have the same problems.

**Comment by degeer** [comment]
Thank you for your comments. We have created a new version: 1.1.2 that deals with some of these issues. We will make additional updates in the coming months.

**Comment by degeer** [comment]
We have created a new version: 1.1.3 which, among other things, updates dar mode colors for visualizations and sparklines, e.g.
<img width="1082" alt="Screenshot 2022-10-24 at 11 45 35" src="https://user-images.githubusercontent.com/282174/197474084-b7cd40a7-0195-47db-a596-7d61fe41ba73.png">
<img width="1049" alt="Screenshot 2022-10-24 at 11 45 41" src="https://user-images.githubusercontent.com/282174/197474090-fed6f4b9-d862-4abf-9114-d918ce80b3a9.png">

**Comment by degeer** [comment]
We have created a new version: 1.1.2 that deals with some additional issues.
